### ISSUE TITLE
Indentation does not meet PEP8

### ISSUE THREAD

**Issue by SBradleyScripts** [TheWickerMan/EmailHandling#1]
Scripts appear to be using a single space as indentation, whilst this is technically possible all code should be modified to use 4 spaces per indent.

https://www.python.org/dev/peps/pep-0008/

**Comment by TheWickerMan** [comment]
Hi SBradleyScripts,

PEP-0008 is a style **guide** for Python programming, however so-longs as the programmer is consistent with their indentations it causes no detriment to the application.
